[package]
name = "csv_to_geojson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
geo = "0.18.0"
geojson = "0.22.2"
serde_json = "1.0.74"
