[package]
name = "read_geojson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.18.0"
geo-types = "0.7.2"
geojson = "0.22.2"
